version: '3'
services:
  dev:
    build: .
    command:  bash -c "npm run local"
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    ports:
      - '3000:3000'
      - '8000:8000'
    tty: true
    stdin_open: true
    environment: 
    - TERM=xterm-256color
    - TZ=Australia/Melbourne